---
- name: Check OS ( Linstor Satellite )
  fail: msg="{{ ansible_distribution }} is Not Supported!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'


- name: Set Facts for Network and Packages Informations
  import_tasks: set-facts.yml
  tags: install, uninstall, create, delete, enable, disable, setup, remove


- name: Enable Firewall
  import_tasks: enable-firewall.yml
  tags: enable, install
  when: ( firewall is defined and firewall == true ) or ( satellite_all is defined and satellite_all == true )


- name: Install Linstor Satellite
  import_tasks: setup-satellite.yml
  tags: setup, install
  when: ( service is defined and service == true ) or ( satellite_all is defined and satellite_all == true )


- name: Uninstall Linstor Satellite
  import_tasks: remove-satellite.yml
  tags: remove, uninstall
  when: ( service is defined and service == true ) or ( satellite_all is defined and satellite_all == true )


- name: Disable Firewall
  import_tasks: disable-firewall.yml
  tags: disable, uninstall
  when: ( firewall is defined and firewall == true ) or ( satellite_all is defined and satellite_all == true )

