---
- name: Check OS
  fail: msg="{{ ansible_distribution }} is Not Supported!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'


#- name: Set Facts for Network and Packages Informations
#  import_tasks: set-ceph-facts.yml
#  tags: install, uninstall, upload, download, init, purge, add, remove, enable, disable, clean, deploy, destroy


- name: Install Linstor Satellite
  import_tasks: install.yml
  tags: install


- name: Uninstall Linstor Satellite
  import_tasks: uninstall.yml
  tags: uninstall

