---
- name: Check OS ( Linstor Satellite )
  fail: msg="{{ ansible_distribution }} is Not Supported!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'


- name: Set Facts for Network and Packages Informations
  import_tasks: set-facts.yml
  tags: install, uninstall, create, delete, enable, disable, setup, remove


- name: Install Linstor Satellite
  import_tasks: install.yml
  tags: setup, create, install


- name: Uninstall Linstor Satellite
  import_tasks: uninstall.yml
  tags: remove, delete, uninstall

