---
- name: Delete LINSTOR Cluster as Satellite Node
  shell: |
    linstor node delete {{ ansible_nodename }}
  register: linstor_create_result
  failed_when: ( linstor_create_result.rc not in [ 0, 10 ] )


- name: Check Satellite is Deleted
  shell: |
    linstor node list | grep SATELLITE  | wc -l
  register: check_satellite_status
  until: check_satellite_status.stdout|int == 0
  retries: 12
  delay: 5
# wait_for: timeout=30

