---
- name: Enable and Start LINSTOR Satellite
  systemd:
    name: linstor-satellite.service
    daemon_reload: yes
    state: restarted
    enabled: yes


- name: Join LINSTOR Cluster as Satellite Node
  shell: |
    linstor node create {{ ansible_nodename }} {{ ansible_all_ipv4_addresses | ipaddr(drbd_replication_network) | first }} \
    --node-type satellite
  register: linstor_create_result
  failed_when: ( linstor_create_result.rc not in [ 0, 10 ] )


- name: Check Satellite is Online
  shell: |
    linstor node list | grep SATELLITE  | grep Online | wc -l
  register: check_satellite_status
  until: check_satellite_status.stdout|int == 3
  retries: 12
  delay: 5


