---
- name: Check if Firewalld is Running ( RHEL )
  shell: systemctl status firewalld
  register: firewalld
  failed_when: ( firewalld.rc not in [ 0, 3, 4 ] )
  when: ansible_os_family == 'RedHat'


- name: Firewalld Ports for LINSTOR Controller/Satellite Connections
  firewalld:
    port: 3376/tcp
    permanent: true
    immediate: true
    state: enabled
  when: firewalld.rc is defined and firewalld.rc == 0


- name: Firewalld Ports for LINSTOR Controller REST Client Connections
  firewalld:
    port: 3370/tcp
    permanent: true
    immediate: true
    state: enabled
  when: firewalld.rc is defined and firewalld.rc == 0


- name: Check if UFW is Running (Ubuntu)
  shell: ufw status
  changed_when: false
  register: ufw
  when: ansible_os_family == 'Debian'


- name: The UFW Ports for LINSTOR Controller/Satellite Connections
  ufw:
    rule: allow
    proto: tcp
    port: "3376"
  when: ufw.rc is defined and 'inactive' not in ufw.stdout


- name: The UFW Ports for LINSTOR Controller REST Client Connections
  ufw:
    rule: allow
    proto: tcp
    port: "3370"
  when: ufw.rc is defined and 'inactive' not in ufw.stdout


- name: Enable and Start LINSTOR Controller
  systemd:
    name: linstor-controller.service
    daemon_reload: yes
    state: restarted
    enabled: yes


#- name: Sleep for 30 Seconds and Continue with Play
#  wait_for: timeout=30


- name: Initialize the LINSTOR Control Node as Pure Controller
  shell: |
    linstor node create {{ ansible_nodename }} {{ ansible_all_ipv4_addresses | ipaddr(drbd_replication_network) | first }} \
    --node-type controller
  register: linstor_create_result
  failed_when: ( linstor_create_result.rc not in [ 0, 10 ] )
  when: "'satellite' not in group_names"


- name: Initialize the LINSTOR Control Node as a Combined Type
  shell: |
    linstor node create {{ ansible_nodename }} {{ ansible_all_ipv4_addresses | ipaddr(drbd_replication_network) | first }} \
    --node-type combined
  register: linstor_create_result
  failed_when: ( linstor_create_result.rc not in [ 0, 10 ] )
  when: "'satellite' in group_names"


- name: Sleep for 30 Seconds and Continue with Play
  shell: |
    linstor node list | grep CONTROLLER | awk '{print $9}'
  register: check_controller_status
  until: check_controller_status.stdout.find("Online") != -1
  retries: 12
  delay: 5

