---
- name: Check OS ( Linstor Controller )
  fail: msg="{{ ansible_distribution }} is Not Supported!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'


- name: Set Facts for Network and Packages Informations
  import_tasks: set-facts.yml
  tags: install, uninstall, enable, disable, create, delete, setup, remove


- name: Enable Firewall
  import_tasks: enable-firewall.yml
  tags: enable, install
  when: ( firewall is defined and firewall == true ) or ( controller_all is defined and controller_all == true )


- name: Install Linstor Controller
  import_tasks: setup-controller.yml
  tags: setup, install
  when: ( service is defined and service == true ) or ( controller_all is defined and controller_all == true )


- name: Uninstall Linstor Controller
  import_tasks: remove-controller.yml
  tags: remove, uninstall
  when: ( service is defined and service == true ) or ( controller_all is defined and controller_all == true )


- name: Disable Firewall
  import_tasks: disable-firewall.yml
  tags: disable, uninstall
  when: ( firewall is defined and firewall == true ) or ( controller_all is defined and controller_all == true )

