---
- name: Enable and Start LINSTOR Controller
  systemd:
    name: linstor-controller.service
    daemon_reload: yes
    state: restarted
    enabled: yes
#- wait_for: timeout=30


- name: Initialize the LINSTOR Control Node as Pure Controller
  shell: |
    linstor node create {{ ansible_nodename }} {{ ansible_all_ipv4_addresses | ipaddr(drbd_replication_network) | first }} \
    --node-type controller
  register: linstor_create_result
  failed_when: ( linstor_create_result.rc not in [ 0, 10 ] )
  when: "'satellite' not in group_names"


- name: Initialize the LINSTOR Control Node as a Combined Type
  shell: |
    linstor node create {{ ansible_nodename }} {{ ansible_all_ipv4_addresses | ipaddr(drbd_replication_network) | first }} \
    --node-type combined
  register: linstor_create_result
  failed_when: ( linstor_create_result.rc not in [ 0, 10 ] )
  when: "'satellite' in group_names"


- name: Sleep for 30 Seconds and Continue with Play
  shell: |
    linstor node list | grep CONTROLLER | awk '{print $9}'
  register: check_controller_status
  until: check_controller_status.stdout.find("Online") != -1
  retries: 12
  delay: 5

