---
- name: Create thin File Backed Storage Pool Directory
  file:
    path: "{{ item.storage_dev }}"
    state: directory
    mode: "{{ item.mode }}"
  with_items: "{{ _storage.filethin }}"


- name: Create the Storage Pool for File-Thin
  shell: |
    linstor storage-pool create {{ item.type }} {{ ansible_nodename }} {{ item.storage_pool }} {{ item.storage_dev }}
  register: create_filethin_storage_pool
  with_items: "{{ _storage.filethin }}"
# failed_when: ( create_filethin_storage_pool.rc not in [ 0, 10 ] )

