---
- name: Delete the File-Thin Storage Pool
  shell: |
    linstor storage-pool delete {{ item.type }} {{ ansible_nodename }} {{ item.storage_pool }}
  register: delete_filethin_storage_pool
  with_items: "{{ _storage.filethin }}"
# failed_when: ( delete_filethin_storage_pool.rc not in [ 0, 10 ] )


- name: Delete thin File Backed Storage Pool Directory
  file:
    path: "{{ item.storage_dev }}"
    state: absent
  with_items: "{{ _storage.filethin }}"

