---
- name: Delete the LVM-Thin Storage Pool
  shell: |
    linstor storage-pool delete {{ ansible_nodename }} {{ item.storage_pool }}
  register: delete_lvmthin_storage_pool
  ignore_errors: true
  with_items: "{{ _storage.lvmthin }}"
# failed_when: ( delete_lvmthin_storage_pool.rc not in [ 0, 10 ] )


- name: Remove Linstor Device Mapper
  shell: |
    dmsetup remove linstor_{{ item.storage_pool }}-{{ item.pool_name }}
  register: remove_linstor_dm
  ignore_errors: true
  with_items: "{{ _storage.lvmthin }}"


#- name: Remove Linstor Device Mapper Tpool
#  shell: |
#    dmsetup remove linstor_{{ item.storage_pool }}-{{ item.pool_name }}-tpool
#  register: remove_linstor_dm_tpool
#  ignore_errors: true
#  with_items: "{{ _storage.lvmthin }}"


- name: Remove Linstor Device Mapper Tdata
  shell: |
    dmsetup remove linstor_{{ item.storage_pool }}-{{ item.pool_name }}_tdata
  register: remove_linstor_dm_tdata
  ignore_errors: true
  with_items: "{{ _storage.lvmthin }}"


- name: Remove Linstor Device Mapper Tmeta
  shell: |
    dmsetup remove linstor_{{ item.storage_pool }}-{{ item.pool_name }}_tmeta
  register: remove_linstor_dm_tmeta
  ignore_errors: true
  with_items: "{{ _storage.lvmthin }}"

