---
- name: Delete the Storage Pool for lvm-thin
  shell: |
    linstor storage-pool delete lvmthin {{ ansible_nodename }} lvm-thin
  register: storage_pool_delete_result
  failed_when: ( storage_pool_delete_result.rc not in [ 0, 10 ] )


- name: Delete Thin LVM on DRBD Pool
  lvol:
    vg: drbdpool
    thinpool: thinpool
    state: absent
    force: true
    # size: 50%VG


- name: Inactive DRBD Pool Volume Group for LINSTOR
  lvg:
    vg: drbdpool
    pvs: "{{ drbd_backing_disk }}"
    force: true
    state: inactive


- name: Remove DRBD Pool Volume Group for LINSTOR
  lvg:
    vg: drbdpool
    pvs: "{{ drbd_backing_disk }}"
    force: true
    state: absent

