---
- name: Add Linstor Reepository
  yum_repository:
    name: "{{ item }}"
    description: Linbit Repository for Linstor
    baseurl: "https://packages.linbit.com/yum/rhel9/{{ item }}/x86_64/"
    enabled: yes
  with_items:
    - "drbd-9"
    - "drbd-proxy-3.2"
    - "drbd-proxy-4"
    - "pacemaker-2"


- name: Copy Linstor RPM Packages
  copy: src={{ item }} dest={{ _linstor.base_path }}/{{ item }} mode=0644 owner=root group=root
  with_items:
    - linstor-controller-1.30.4-1.el9.noarch.rpm
    - python-linstor-1.25.0-1.noarch.rpm
    - linstor-client-1.23.2-1.noarch.rpm
    - linstor-gui-1.9.3-1.noarch.rpm
    - linstor-common-1.30.4-1.el9.noarch.rpm
    - linstor-satellite-1.30.4-1.el9.noarch.rpm
    - kmod-drbd-9.2.13_5.14.0_503.33.1-1.x86_64.rpm


- name: Install Linstor RPM Packages
  package:
    name: "{{ _linstor.base_path }}/{{ item }}"
    state: present
    disable_gpg_check: yes
  # async: 360
  # poll: 5
  with_items:
    - linstor-controller-1.30.4-1.el9.noarch.rpm
    - linstor-satellite-1.30.4-1.el9.noarch.rpm
    - linstor-client-1.23.2-1.noarch.rpm
    - linstor-gui-1.9.3-1.noarch.rpm
    - linstor-common-1.30.4-1.el9.noarch.rpm
    - python-linstor-1.25.0-1.noarch.rpm
    - kmod-drbd-9.2.13_5.14.0_503.33.1-1.x86_64.rpm


- name: Install DRBD Packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - drbd


- name: Add DRBD Module
  modprobe:
    name: drbd
    state: present


- name: Save DRBD Kernel Module Parameters
  template:
    src: drbd.conf.j2
    dest: "/etc/modules-load.d/{{ item }}.conf"
    mode: 0644
  with_items:
    - drbd


- name: Reboot Required
  shell: ( /bin/sleep 5; /sbin/shutdown -r now "Ansible Updates Triggered" ) &
  register: reboot_required
  ignore_errors: true
  async: 120
  poll: 0
  notify:
    - Waiting for Server to Come Back after Restart


- meta: flush_handlers

