---
- name: Install Linstor Packages for RedHat/CentOS/Rocky
  import_tasks: install-rh-pkgs.yml
  when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky"


- name: Install Linstor Packages for Ubuntu/Debian
  import_tasks: install-ubt-pkgs.yml
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

