---
- name: Check OS
  fail: msg="{{ ansible_distribution }} is Not Supported!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'


#- name: Set Facts for Network and Packages Informations
#  import_tasks: set-facts.yml
#  tags: install, uninstall, upload, download, init, purge, add, remove, enable, disable, clean, deploy, destroy


#- name: Register Nodes and Install Packages
#  import_tasks: install-pkgs.yml
#  tags: prepare
#  when: ( remote is defined and remote == true )


- name: Install Local Packages
  import_tasks: install-local-pkgs.yml
  tags: prepare


- name: Uninstall Linstor Controller
  import_tasks: uninstall-pkgs.yml
  tags: clean

