---
- name: Check OS ( Linstor Cluster )
  fail: msg="{{ ansible_distribution }} is Not Supported!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'


- name: Set Facts for Network and Packages Informations
  import_tasks: set-facts.yml
  tags: prepare, clean, install, uninstall, enable, disable, create, delete


- name: Install Linstor Packages
  import_tasks: install-pkgs.yml
  tags: prepare, setup, install


- name: Uninstall Linstor Controller
  import_tasks: uninstall-pkgs.yml
  tags: clean, remove, uninstall

