---
- name: Uninstall Linstor Packages for RedHat/CentOS/Rocky
  import_tasks: uninstall-rh-pkgs.yml
  when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky"


- name: Uninstall Linstor Packages for Ubuntu/Debian
  import_tasks: uninstall-ubt-pkgs.yml
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

