---
- name: Remove Physical Volumes
  shell: |
    pvremove -y -ff {{ item }}
  register: remove_pvs
  ignore_errors: true
  with_items: "{{ drbd_backing_disk }}"
- debug: msg={{ remove_pvs }}


- name: Purge Block Devices
  shell: |
    dd if=/dev/zero of={{ item }} bs=4096 count=1 conv=notrunc
  register: purge_block_devices
  ignore_errors: true
  with_items: "{{ drbd_backing_disk }}"
- debug: msg={{ purge_block_devices }}


- name: Wipe Filesystem in NVME Devices
  shell: |
    wipefs -a {{ item }}
  register: wipefs_nvme_devices
  ignore_errors: true
  with_items: "{{ drbd_backing_disk }}"
- debug: msg={{ wipefs_nvme_devices }}


- name: Delete Zap in NVME Devices
  shell: |
    sgdisk --zap-all --delete {{ item }}
  register: delete_zap_nvme_devices
  ignore_errors: true
  with_items: "{{ drbd_backing_disk }}"
- debug: msg={{ delete_zap_nvme_devices }}


- name: Discard Block ID
  shell: |
    blkdiscard {{ item }}
  register: discard_block_id
  ignore_errors: true
  with_items: "{{ drbd_backing_disk }}"
- debug: msg={{ discard_block_id }}

