---
- name: Create thin File Backed Storage Pool Directory
  file:
    path: /var/lib/linstor/file-thin-storage-pool
    state: directory
    mode: '0755'


- name: Create the Storage Pool for File-Thin
  shell: |
    linstor storage-pool create filethin {{ ansible_nodename }} file-thin /var/lib/linstor/file-thin-storage-pool
  register: storage_pool_create_result
  failed_when: ( storage_pool_create_result.rc not in [ 0, 10 ] )

