---
- name: Create the Physical Storage Pool
  shell: |
    linstor physical-storage create-device-pool --storage-pool {{ item.storage_pool }} \
    --pool-name {{ item.pool_name }} {{ item.type }} {{ ansible_nodename }} {{ item.storage_dev }}
  register: create_storage_pool
  with_items: "{{ _linstor.storage }}"
- debug: msg={{ create_storage_pool }}
  # failed_when: ( storage_pool_create_result.rc not in [ 0, 10 ] )


- name: Cancel Automatic Eviction
  shell: |
    linstor controller set-property DrbdOptions/AutoEvictAllowEviction
  register: cancle_auto_evict
- debug: msg={{ cancle_auto_evict }}


- name: Verify that All Storage Pools are Created and Report the Expected Size
  shell: |
    linstor resource-group list
  register: verify_all_storage_pools
- debug: msg={{ verify_all_storage_pools }}


- name: List All Storage Pools
  shell: |
    linstor storage-pool list
  register: list_all_storage_pools
- debug: msg={{ list_all_storage_pools }}

