---
- name: Create DRBD Pool Volume Group for LINSTOR
  lvg:
    vg: drbdpool
    pvs: "{{ drbd_backing_disk }}"


- name: Create Thin LVM on DRBD Pool
  lvol:
    vg: drbdpool
    thinpool: thinpool
    size: 50%VG


- name: Create the Storage Pool for lvm-thin
  shell: |
    linstor storage-pool create lvmthin {{ ansible_nodename }} lvm-thin drbdpool/thinpool
  register: storage_pool_create_result
  failed_when: ( storage_pool_create_result.rc not in [ 0, 10 ] )

