---
- name: Delete the Storage Pool for File-Thin
  shell: |
    linstor storage-pool delete filethin {{ ansible_nodename }} file-thin
  register: storage_pool_delete_result
  failed_when: ( storage_pool_delete_result.rc not in [ 0, 10 ] )


- name: Delete thin File Backed Storage Pool Directory
  file:
    path: /var/lib/linstor/file-thin-storage-pool
    state: absent

