---
- name: Create the Storage Pool for
  shell: |
    linstor physical-storage create-device-pool --storage-pool nvme_pool \
    --pool-name nvme_pool lvmthin {{ ansible_nodename }} /dev/nvme0n1
  register: storage_pool_create_result
  failed_when: ( storage_pool_create_result.rc not in [ 0, 10 ] )


- name: Cancel Automatic Eviction
  shell: |
    linstor controller set-property DrbdOptions/AutoEvictAllowEviction
  register: cancle_auto_evict


- name: Verify that all storage pools are created and report the expected size
  shell: |
    linstor resource-group list
  register: verify_all_storage_pools
- debug: msg={{ verify_all_storage_pools }}

