---
- name: Check OS ( Storage Pool )
  fail: msg="{{ ansible_distribution }} is Not Supported!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'


#- name: Set Facts for Network and Packages Informations
#  import_tasks: set-ceph-facts.yml
#  tags: install, uninstall, upload, download, init, purge, add, remove, enable, disable, clean, deploy, destroy


- name: Cleanup Block Devices
  import_tasks: cleanup-devices.yml
  tags: install


- name: Install Linstor Storage Pool
  import_tasks: install-nvme.yml
  tags: install


- name: Uninstall Linstor Storage Pool
  import_tasks: uninstall-nvme.yml
  tags: uninstall


- name: Cleanup Block Devices
  import_tasks: cleanup-devices.yml
  tags: uninstall


