---
- name: Check OS ( Linstor Storage Pool )
  fail: msg="{{ ansible_distribution }} is Not Supported!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'


- name: Set Facts for Network and Packages Informations
  import_tasks: set-facts.yml
  tags: install, uninstall, create, delete, setup, remove, clean


- name: Create Linstor Physical Storage Pool
  import_tasks: create-storage-pool.yml
  tags: setup, create, install


- name: Delete Linstor Physical Storage Pool
  import_tasks: delete-storage-pool.yml
  tags: remove, delete, uninstall


- name: Cleanup Block Devices
  import_tasks: cleanup-devices.yml
  tags: clean, destroy, uninstall
  when: ( dev is defined and dev == true ) or ( storage_all is defined and storage_all == true )

