---
- name: Delete the Storage Pool for
  shell: |
    linstor storage-pool delete {{ ansible_nodename }} nvme_pool
  register: storage_pool_delete_result
  failed_when: ( storage_pool_delete_result.rc not in [ 0, 10 ] )

