---
- name: Delete LINSTOR Cluster as Satellite Node
  shell: |
    linstor node delete {{ ansible_nodename }}
  register: linstor_create_result
  failed_when: ( linstor_create_result.rc not in [ 0, 10 ] )


- name: Check Satellite is Deleted
  shell: |
    linstor node list | grep SATELLITE  | wc -l
  register: check_satellite_status
  until: check_satellite_status.stdout|int == 0
  retries: 12
  delay: 5
# wait_for: timeout=30


- name: Disable and Stop LINSTOR Satellite
  systemd:
    name: linstor-satellite.service
    daemon_reload: yes
    state: stopped
    enabled: no


- name: The UFW Ports for LINSTOR Satellite
  ufw:
    rule: deny
    proto: tcp
    port: "3366"
  when: ufw.rc is defined and 'inactive' not in ufw.stdout


- name: The UFW Ports for DRBD
  ufw:
    rule: deny
    proto: tcp
    port: 7000:8000
  when: ufw.rc is defined and 'inactive' not in ufw.stdout


- name: Check if UFW is Running (Ubuntu)
  shell: ufw status
  changed_when: false
  register: ufw
  when: ansible_os_family == 'Debian'


- name: The Firewalld Ports for DRBD
  firewalld:
    port: 7000-8000/tcp
    permanent: true
    immediate: true
    state: disabled
  when: firewalld.rc is defined and firewalld.rc == 0


- name: The Firewalld Ports for LINSTOR Satellite
  firewalld:
    port: 3366/tcp
    permanent: true
    immediate: true
    state: disabled
  when: firewalld.rc is defined and firewalld.rc == 0


- name: Check if Firewalld is Running ( RHEL )
  shell: systemctl status firewalld
  register: firewalld
  failed_when: ( firewalld.rc not in [ 0, 3, 4 ] )
  when: ansible_os_family == 'RedHat'


- name: Remove linstor-client.conf
  file:
    path: /etc/linstor/linstor-client.conf
    state: absent


- name: Gather Facts from Controller ( needed when playbook --limit excludes controller )
  setup:
  delegate_to: "{{item}}"
  delegate_facts: True
  loop: "{{groups['controller']}}"

